[package]
name = "finance_overview_training"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.1"}
axum-server = {version ="0.4.0", features=["tls-rustls"]}
futures = "0.3"
once_cell = { version = "1.10.0"}
rust-ini = {version = "0.18.0"}
tokio = { version = "1.0", features = ["full"] }

[dependencies.mongodb]
version = "2.2.0"
default-features = false
features = ["async-std-runtime"]