[package]
name = "finance_overview_training"
version = "0.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.11.1"
async-mongodb-session = {version = "2.0.0", git = "https://github.com/TiloPapke/async-mongodb-session.git"}
axum = { version = "0.5.1"}
axum-server = {version ="0.4.0", features=["tls-rustls"]}
futures = "0.3"
log = "0.4.16"
log4rs = "1.1.0"
once_cell = { version = "1.10.0"}
rust-ini = {version = "0.18.0"}
secrecy = {version = "0.8.0", features = ["serde", "alloc"] }
serde ="1"
tokio = { version = "1.0", features = ["full"] }

[dependencies.mongodb]
version = "2.2.1"
default-features = false
features = ["async-std-runtime"]