[package]
name = "FinanceOverViewTraining"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5.1"}
tokio = { version = "1.0", features = ["full"] }