[package]
name = "finance_overview_training"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.100"
argon2 = "0.5.3"
askama = "0.15.0"

#forcing others to higher version
#time = "0.3.44"

async-session = "3.0.0"
async-trait = "0.1.89" # see https://stackoverflow.com/questions/65921581/how-can-i-define-an-async-method-in-a-trait and https://crates.io/crates/async-trait

axum = { version = "0.8.8"}
axum-extra = { version = "0.12.3", features = ["typed-header", "cookie"] }
axum-server = {version = "0.8", features = ["tls-rustls"] }
axum_session = { version = "0.17.0" }
axum_session_mongo = { version = "0.5.1" }

futures = "0.3"

log = "0.4.29"
log4rs = "1.4.0"
mail-send = "0.5.2"
once_cell = { version = "1.21.3"}
rand = "0.8.5" # can not go higher because of async-mongodb-session = "3.0.0" and async-session = "3.0.0"
regex-automata = "0.4.13"
rust-ini = {version = "0.21.3"}
secrecy = {version = "0.10.3", features = ["serde"] }
serde ="1"
tokio = { version = "1.48", features = ["full"] }


[dependencies.mongodb]
version = "3.4.1"
default-features = true
features = ["sync"]