[package]
name = "finance_overview_training"
version = "0.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.21"
argon2 = "0.4.0"
askama = "0.11.1"
async-mongodb-session = {version = "2.0.0", git = "https://github.com/TiloPapke/async-mongodb-session.git"}
# can not go higher with async-session because of async-mongodb-session
async-session = "2.0.1"
axum = { version = "0.5.1", features = ["headers"]}
axum-server = {version ="0.4.0", features=["tls-rustls"]}
futures = "0.3"
#http-auth-basic = "0.3.3"
log = "0.4.16"
log4rs = "1.1.0"
mail-send = "0.2.3"
once_cell = { version = "1.10.0"}
rand = "0.8.5"
rust-ini = {version = "0.18.0"}
secrecy = {version = "0.8.0", features = ["serde", "alloc"] }
serde ="1"
tokio = { version = "1.0", features = ["full"] }
# mongodb uses uuid 0.8.2
uuid = { version = "0.8.2", features = ["v4", "serde"] }

[dependencies.mongodb]
version = "2.2.1"
default-features = false
features = ["async-std-runtime", "bson-uuid-0_8"]