#Hint, if you want to use your own settings please use a different settings file.
#This file might be changed with future commits

#for clarification:
# set debug level: logged messages level
# error: [error]
# warn: [error, warn]
# info: [error, warn, info]
# debug: [error, warn, info, debug]
# trace: [error, warn, info, debug, trace]

# refresh intervall
refresh_rate: 30 seconds

#different output places
appenders:
  stdout:
    kind: console # write to console
  fileoutput:
    kind: file # write to file
    path: "log/FinanceOverViewLog.log" #name of the file
    encoder:
      pattern: "{d} - {m}{n}" # format of output files

# general settings, used by all log call that have no logger set or that use a logger that is not defined
root:
  level: warn
  appenders:
    - stdout

# define loggers
loggers:
  # Raise the maximum log level for events sent to the "app::backend::db" logger to "info"
  app::FinanceOverView: #identifier of this Program (last column ":" is needed!)
    # log level for this logger
    level: trace
    # list of output places
    appenders:
      - fileoutput
      - stdout
    additive: false